stages:
  - test
  - build
  - release-bindings
  - deploy-goerli
  - deploy-mainnet

# Sets ENV_NAME=ENV_VALUE in shell and gitlab ci project ci/cd variables
# ENV_NAME - variable name
# ENV_VALUE - variable value
# ENV_ENV - variable environment (leave unset for all of the environments)
.set-env: &set-env
  - echo "Setting env variable $ENV_NAME=$ENV_VALUE in $ENV_ENV environment"
  - if [ -z "$ENV_ENV" ]; then export ENV_ENV="*"; fi
  - 'declare "$ENV_NAME=$ENV_VALUE" &&
    curl -sS --request PUT --header "PRIVATE-TOKEN: $GITLAB_TOKEN"
    "$CI_API_V4_URL/projects/$CI_PROJECT_ID/variables/$ENV_NAME"
    --form "value=$ENV_VALUE"
    --form "environment_scope=$ENV_ENV"
    --form "filter[environment_scope]=$ENV_ENV"'
  - unset ENV_NAME ENV_VALUE ENV_ENV

test:
  stage: test
  image: node:14-buster
  allow_failure: true
  only:
    - branches
  script:
    - cd ./Goerli/clonefactory/ && yarn install && make test
  artifacts:
    paths:
      - Goerli/clonefactory/node_modules

compile-contracts:
  stage: build
  image: node:14-buster
  needs: ["test"]
  script:
    - cd ./Goerli/clonefactory/ && yarn install && make compile
  artifacts:
    paths:
      - Goerli/clonefactory/abi
      - Goerli/clonefactory/artifacts
      - Goerli/clonefactory/cache
      - Goerli/clonefactory/node_modules

build-contracts-go:
  stage: build
  needs: ["compile-contracts"]
  image: ethereum/client-go:alltools-stable
  script: cd ./Goerli/clonefactory && ./build-go.sh
  artifacts:
    untracked: true
    paths:
      - Goerli/clonefactory/bindings-go

build-contracts-js:
  stage: build
  needs: ["compile-contracts"]
  image: node:14-buster
  script: cd ./Goerli/clonefactory && make build-js
  artifacts:
    untracked: true
    paths:
      - Goerli/clonefactory/bindings-js

deploy-lumerintoken-dev-stg:
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/ &&
      make deploy-lumerin &&
      export ENV_NAME="LUMERIN_TOKEN_ADDR" ENV_VALUE=$(cat lumerin-addr.tmp)
    - *set-env

deploy-lumerintoken-lmn:
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/ &&
      make deploy-lumerin &&
      export ENV_NAME="LUMERIN_TOKEN_ADDR" ENV_VALUE=$(cat lumerin-addr.tmp) ENV_ENV="lmn"
    - *set-env

deploy-clonefactory-dev:
  variables:
    LUMERIN_TOKEN_ADDR: ""
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  environment:
    name: dev
    url: $DYNAMIC_ENVIRONMENT_URL
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/
    # - make deploy-clonefactory
    - echo "test-value" > clonefactory-addr.tmp
    - export ENV_NAME="CLONEFACTORY_ADDR" ENV_VALUE=$(cat clonefactory-addr.tmp) ENV_ENV="dev"
    - *set-env
    # - make populate-contracts
    - export DYNAMIC_ENVIRONMENT_URL="https://goerli.etherscan.io/address/$(cat clonefactory-addr.tmp)"
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

deploy-clonefactory-stg:
  variables:
    LUMERIN_TOKEN_ADDR: ""
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  environment: stg
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/
    - make deploy-clonefactory
    - export ENV_NAME="CLONEFACTORY_ADDR" ENV_VALUE=$(cat clonefactory-addr.tmp) ENV_ENV="stg"
    - *set-env
    - make populate-contracts

deploy-clonefactory-lmn:
  variables:
    LUMERIN_TOKEN_ADDR: ""
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  environment: lmn
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/
    - make deploy-clonefactory
    - export ENV_NAME="CLONEFACTORY_ADDR" ENV_VALUE=$(cat clonefactory-addr.tmp) ENV_ENV="lmn"
    - *set-env
    - make populate-contracts

release-contracts-go:
  stage: release-bindings
  needs: ["build-contracts-go"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_GO ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cd ./Goerli/clonefactory/ && make release-go

release-contracts-js:
  stage: release-bindings
  needs: ["build-contracts-js"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_JS ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cd ./Goerli/clonefactory/ && make release-js
