stages:
  - build
  - test
  - build-test
  - release-bindings
  - update-contracts
  - contract-functions
  - whitelist-clonefactory
  - populate-hr-contracts
  - deploy-contracts

# Tags for all jobs
.tags-dev: &tags-dev
  - devops
  - bedrock
  - docker
  - titanio-dev

.tags-stg: &tags-stg
  - devops
  - bedrock
  - docker
  - titanio-stg

.tags-lmn: &tags-lmn
  - devops
  - bedrock
  - docker
  - titanio-lmn

variables:
  CI_GROUP_ID: "15533332" # id of the proxy group
  NODE_IMAGE: "node:20-buster"

# Sets ENV_NAME=ENV_VALUE in shell and in gitlab ci group variables
# ENV_NAME - variable name
# ENV_VALUE - variable value
# ENV_ENV - variable environment (leave unset for all of the environments)
#
# Gitlab api has a bug: PUT is not working correctly with environment field
# https://gitlab.com/gitlab-org/gitlab/-/issues/9912
# DELETE+POST is used instead
.set-env: &set-env
  - echo "Setting env variable $ENV_NAME=$ENV_VALUE in $ENV_ENV environment"
  - if [ -z "$ENV_ENV" ]; then export ENV_ENV="*"; fi
  - declare "$ENV_NAME=$ENV_VALUE" # sets env variable to the value also in the local shell
  - 'curl -sS --request DELETE
    --header "PRIVATE-TOKEN: $GITLAB_TOKEN"
    "$CI_API_V4_URL/groups/$CI_GROUP_ID/variables/$ENV_NAME?filter\[environment_scope\]=$ENV_ENV"'
  - 'curl -sS --fail --request POST
    --header "PRIVATE-TOKEN: $GITLAB_TOKEN"
    "$CI_API_V4_URL/groups/$CI_GROUP_ID/variables"
    --form "key=$ENV_NAME"
    --form "value=$ENV_VALUE"
    --form "environment_scope=$ENV_ENV"'
  - unset ENV_NAME ENV_VALUE ENV_ENV

# Downloads artifacts from previous successful upgradeable smart-contract deploy
# Required variables:
# UPGRADE_JOB_NAME - name of the job that upgrades the upgradeable smart-contract
# DEPLOY_JOB_NAME - name of the job that deploys the upgradeable smart-contract
.download-smart-contract-artifacts: &download-smart-contract-artifacts
  - echo "Downloading artifacts from previous successful deploy" 
  - echo "Downloading artifacts from $UPGRADE_JOB_NAME"
  - | 
    set +e
    curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$UPGRADE_JOB_NAME"
    if [ $? -ne 0 ]; then
      echo "cannot find update artifacts, trying from $DEPLOY_JOB_NAME"
      curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$DEPLOY_JOB_NAME"
      if [ $? -ne 0 ]; then
        echo "cannot find deploy artifacts, using artifacts from source control"
      fi
    fi
    set -e
  - if [ -f artifacts.zip ]; then unzip artifacts.zip "./.openzeppelin" -d . && echo "artifacts downloaded";  fi
  - if [ ! -f artifacts.zip ]; then echo "artifacts not downloaded"; fi

# Deploys clonefactory to the blockchain using env variables from the corresponding environment
# Updates the environment url to the etherscan url of the contract
# TODO: fix hardcoded etherscan url
.deploy_clonefactory_template: &deploy_clonefactory_template
  stage: deploy-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  artifacts:
    paths:
      - .openzeppelin
    reports:
      dotenv: deploy.env
  environment:
    name: dev # The environment.name should be overriden
    url: $DYNAMIC_ENVIRONMENT_URL
  script:
    - make deploy-clonefactory
    - export ENV_NAME="CLONE_FACTORY_ADDRESS" ENV_VALUE=$(cat clonefactory-addr.tmp) ENV_ENV=$CI_ENVIRONMENT_SLUG
    - *set-env
    - export DYNAMIC_ENVIRONMENT_URL="https://sepolia.arbiscan.io/address/$(cat clonefactory-addr.tmp)"
    - cd ../..
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env

.deploy_faucet_template: &deploy_faucet_template
  stage: deploy-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  artifacts:
    paths:
      - .openzeppelin
  environment:
    name: dev # The environment.name should be overriden
  script:
    - make deploy-faucet

.update_clonefactory_template: &update_clonefactory_template
  stage: update-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  artifacts:
    paths:
      - .openzeppelin
  environment:
    name: dev
  script:
    - export UPGRADE_JOB_NAME="update-clonefactory-$CI_ENVIRONMENT_SLUG" DEPLOY_JOB_NAME="deploy-clonefactory-$CI_ENVIRONMENT_SLUG"
    - *download-smart-contract-artifacts
    - make update-clonefactory

.update_implementation_template: &update_implementation_template
  stage: update-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  artifacts:
    paths:
      - .openzeppelin
  environment:
    name: dev
  script:
    - export UPGRADE_JOB_NAME="update-implementation-$CI_ENVIRONMENT_SLUG" DEPLOY_JOB_NAME="deploy-clonefactory-$CI_ENVIRONMENT_SLUG"
    - *download-smart-contract-artifacts
    - make update-implementation

.deploy_hr_contracts_template: &deploy_hr_contracts_template
  stage: populate-hr-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  environment:
    name: dev
  script:
    - make populate-contracts

.whitelist_clonefactory_template: &whitelist_clonefactory_template
  stage: whitelist-clonefactory
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  environment:
    name: dev
    action: prepare
  script:
    - make whitelist-clonefactory

.deploy_lumerintoken_dev_stg: &deploy_lumerintoken_dev_stg
  stage: deploy-contracts
  needs: ["compile-contracts", "test", "build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  script: 
    - make deploy-lumerin
    - export ENV_NAME="LUMERIN_TOKEN_ADDRESS" ENV_VALUE=$(cat lumerin-addr.tmp)
    - *set-env

compile-contracts:
  stage: build
  image: $NODE_IMAGE
  tags: *tags-dev
  environment:
    name: dev
    action: prepare
  script:
    - yarn install && make compile
  artifacts:
    paths:
      - abi
      - artifacts
      - cache
      - node_modules

build-contracts-go:
  stage: build
  needs: ["compile-contracts"]
  image: ethereum/client-go:alltools-stable
  tags: *tags-lmn
  before_script:
    - apk --no-cache add jq
  script: 
    - ./build-go.sh
  artifacts:
    untracked: true
    paths:
      - build-go

build-contracts-js:
  stage: build
  needs: ["compile-contracts"]
  image: $NODE_IMAGE
  tags: *tags-dev
  script: make build-js
  artifacts:
    untracked: true
    paths:
      - build-js

test:
  environment: test
  stage: test
  image: $NODE_IMAGE
  tags: *tags-dev
  allow_failure: false
  needs: ["build-contracts-js", "compile-contracts"]
  only:
    - branches    
  script:
    - yarn install
    - make test

# TODO: decide how to run upgrade tests when we have different versions of the smart-contract in the target branch
# it could be done by running the upgrade tests against particular commit, or maybe by using predefined scripts versioned
# together with the particular smart-contract version
#
# test-upgrade:
#   environment: test
#   stage: test
#   image: $NODE_IMAGE
#   tags: *tags-dev
#   allow_failure: false
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#   script:
#     - yarn install
#     - make compile
#     - make build-js
#     - BRANCH_TO_TEST_AGAINST=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME make test-upgrade

deploy-lumerintoken-dev:
  <<: *deploy_lumerintoken_dev_stg
  environment:
    name: dev
  tags: *tags-dev

deploy-lumerintoken-stg:
  <<: *deploy_lumerintoken_dev_stg
  environment:
    name: stg
  tags: *tags-stg

# Will be used only when we will have a separate lumerin token for LMN environment
#
# deploy-lumerintoken-lmn:
#   stage: deploy-contracts
#   needs: ["compile-contracts"]
#   image: $NODE_IMAGE
#   tags: *tags-lmn
#   when: manual
#   only:
#     - main
#   script:
#     - make deploy-lumerin
#     - export ENV_NAME="LUMERIN_TOKEN_ADDRESS" ENV_VALUE=$(cat lumerin-addr.tmp) ENV_ENV="lmn"
#     - *set-env

update-clonefactory-dev:
  <<: *update_clonefactory_template
  environment:
    name: dev
  tags: *tags-dev

update-clonefactory-stg:
  <<: *update_clonefactory_template
  environment:
    name: stg
  tags: *tags-stg

update-clonefactory-lmn:
  <<: *update_clonefactory_template
  environment:
    name: lmn
  tags: *tags-lmn

update-implementation-dev:
  <<: *update_implementation_template
  environment:
    name: dev
  tags: *tags-dev

update-implementation-stg:
  <<: *update_implementation_template
  environment:
    name: stg
  tags: *tags-stg

update-implementation-lmn:
  <<: *update_implementation_template
  environment:
    name: lmn
  tags: *tags-lmn

whitelist-clonefactory-dev:
  <<: *whitelist_clonefactory_template
  environment:
    name: dev
  tags: *tags-dev
  # only:
  #   - dev

whitelist-clonefactory-stg:
  <<: *whitelist_clonefactory_template
  environment:
    name: stg
  tags: *tags-stg
  # only:
  #   - stg

whitelist-clonefactory-lmn:
  <<: *whitelist_clonefactory_template
  environment:
    name: lmn
  tags: *tags-lmn
  # only:
  #   - lmn

deploy-clonefactory-dev:
  <<: *deploy_clonefactory_template
  environment:
    name: dev
  tags: *tags-dev
  # only:
  #   - dev

deploy-clonefactory-stg:
  <<: *deploy_clonefactory_template
  environment:
    name: stg
  tags: *tags-stg
  # only:
  #   - stg

deploy-clonefactory-lmn:
  <<: *deploy_clonefactory_template
  environment:
    name: lmn
  tags: *tags-lmn
  # only:
  #   - main

deploy-faucet-dev:
  <<: *deploy_faucet_template
  environment:
    name: dev
  tags: *tags-dev
  # only:
  #   - dev

deploy-faucet-stg:
  <<: *deploy_faucet_template
  environment:
    name: stg
  tags: *tags-stg
  # only:
  #   - stg

deploy-faucet-lmn:
  <<: *deploy_faucet_template
  environment:
    name: lmn
  tags: *tags-lmn
  # only:
  #   - lmn

populate-hr-contracts-dev:
  <<: *deploy_hr_contracts_template
  needs: ["compile-contracts", "build-contracts-js"]
  environment:
    name: dev
  tags: *tags-dev
  # only:
  #   - dev

populate-hr-contracts-stg:
  <<: *deploy_hr_contracts_template
  needs: ["compile-contracts", "build-contracts-js"]
  environment:
    name: stg
  tags: *tags-stg
  # only:
  #   - stg

populate-hr-contracts-lmn:
  <<: *deploy_hr_contracts_template
  needs: ["compile-contracts", "build-contracts-js"]
  environment:
    name: lmn
  tags: *tags-lmn
  # only:
  #   - main

release-contracts-go:
  stage: release-bindings
  needs: ["build-contracts-go"]
  image: $NODE_IMAGE
  when: manual
  tags: *tags-lmn
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_GO ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - make release-go

release-contracts-js:
  stage: release-bindings
  needs: ["build-contracts-js"]
  image: $NODE_IMAGE
  when: manual
  tags: *tags-lmn
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_JS ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - make release-js

release-contracts-audit:
  stage: release-bindings
  needs: ["release-contracts-js", "release-contracts-go"]
  image: $NODE_IMAGE
  # when: manual
  tags: *tags-lmn
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_SMART_CONTRACTS ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - make update-public-contracts

set-fee-recipient-dev:
  stage: contract-functions
  image: $NODE_IMAGE
  when: manual
  environment: dev
  tags: *tags-dev
  before_script:
    - apt-get -yq update && apt-get -yqq install
  script:
    - make set-fee-recipient

set-fee-recipient-stg:
  stage: contract-functions
  image: $NODE_IMAGE
  when: manual
  environment: stg
  tags: *tags-stg
  before_script:
    - apt-get -yq update && apt-get -yqq install
  script:
    - make set-fee-recipient

set-fee-recipient-lmn:
  stage: contract-functions
  image: $NODE_IMAGE
  when: manual
  environment: lmn
  tags: *tags-lmn
  before_script:
    - apt-get -yq update && apt-get -yqq install
  script:
    - make set-fee-recipient