stages:
  - test
  - build
  - release-bindings
  - deploy-goerli
  - deploy-mainnet

test:
  stage: test
  image: node:14-buster
  allow_failure: true
  only:
    - branches
  script:
    - cd ./Goerli/clonefactory/ && yarn install && yarn test
    - cd ./Goerli/lumerintoken/ && yarn install && yarn test
  artifacts:
    paths:
      - Goerli/lumerintoken/node_modules
      - Goerli/clonefactory/node_modules

compile-contracts:
  stage: build
  image: node:14-buster
  needs: ["test"]
  script:
    - cd ./Goerli/clonefactory/ && yarn install && yarn compile
  artifacts:
    paths:
      - Goerli/clonefactory/abi
      - Goerli/clonefactory/artifacts
      - Goerli/clonefactory/cache
      - Goerli/clonefactory/node_modules

build-contracts-go:
  stage: build
  needs: ["compile-contracts"]
  image: ethereum/client-go:alltools-stable
  script: cd ./Goerli/clonefactory && ./bindings-go.sh
  artifacts:
    untracked: true
    paths:
      - Goerli/clonefactory/bindings-go

build-contracts-js:
  stage: build
  needs: ["compile-contracts"]
  image: node:14-buster
  script: cd ./Goerli/clonefactory && ./bindings-js.sh
  artifacts:
    untracked: true
    paths:
      - Goerli/clonefactory/bindings-js

deploy-lumerintoken:
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  environment: goerli
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/ && yarn deploy-lumerin

deploy-clonefactory:
  variables:
    LUMERIN_TOKEN_ADDR: ""
  stage: deploy-goerli
  needs: ["compile-contracts"]
  image: node:14-buster
  environment: goerli
  when: manual
  # only:
  #   - main
  script:
    - cd ./Goerli/clonefactory/ && yarn deploy-clonefactory

release-contracts-go:
  stage: release-bindings
  needs: ["build-contracts-go"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_GO ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cd ./Goerli/clonefactory/ && make release-go

release-contracts-js:
  stage: release-bindings
  needs: ["build-contracts-js"]
  image: node:14-buster
  when: manual
  # only:
  #   - main
  before_script:
    - apt-get -yq update && apt-get -yqq install openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - cp $SSH_KEY_CONTRACTS_JS ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cd ./Goerli/clonefactory/ && make release-js
