stages:
  - test
  - build
  - release-bindings
  - deploy-goerli
  - deploy-mainnet

test:
  stage: test
  image: node:14-buster
  only:
    - branches
  script:
    - cd ./Goerli/clonefactory/ && yarn install && yarn test
    - cd ./Goerli/lumerintoken/ && yarn install && yarn test
  artifacts:
    paths:
      - Goerli/lumerintoken/node_modules
      - Goerli/clonefactory/node_modules

compile-lumerintoken:
  stage: build
  image: node:14-buster
  script:
    - cd ./Goerli/lumerintoken/ && yarn install && yarn compile
  artifacts:
    paths:
      - Goerli/lumerintoken/abi
      - Goerli/lumerintoken/artifacts
      - Goerli/lumerintoken/cache
      - Goerli/lumerintoken/node_modules

compile-clonefactory:
  stage: build
  image: node:14-buster
  needs: ["test"]
  script:
    - cd ./Goerli/clonefactory/ && yarn install && yarn compile
  artifacts:
    paths:
      - Goerli/clonefactory/abi
      - Goerli/clonefactory/artifacts
      - Goerli/clonefactory/cache
      - Goerli/clonefactory/node_modules

build-clonefactory-go:
  stage: build
  needs: ["compile-clonefactory"]
  image: ethereum/client-go:alltools-stable
  script: cd ./Goerli/clonefactory && ./bindings-golang.sh
  artifacts:
    paths:
      - Goerli/clonefactory/go

deploy-lumerintoken:
  stage: release-goerli
  needs: ["compile-lumerintoken"]
  image: node:14-buster
  environment: goerli
  when: manual
  only:
    - main
  script:
    - cd ./Goerli/clonefactory/ && yarn deploy

deploy-clonefactory:
  variables:
    LUMERIN_TOKEN_ADDR: ""
  stage: release-goerli
  needs: ["compile-clonefactory"]
  image: node:14-buster
  environment: goerli
  when: manual
  only:
    - main
  script:
    - cd ./Goerli/clonefactory/ && yarn deploy

release-go-bindings:
  stage: release-bindings
  needs: ["build-clonefactory-go"]
  image: node:14-buster
  when: manual
  only:
    - main
  script:
    - cd ./Goerli/clonefactory/ && ./release-go-bindings.sh
